{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "f16f3b46",
   "metadata": {},
   "outputs": [],
   "source": [
    "#==========================================================================================\n",
    "### FUNCTIONS ###\n",
    "#==========================================================================================\n",
    "def map_function(row):\n",
    "    try:\n",
    "        return (row['Passenger_id'], (1, row['Distance_km'], row['Total_flight_time_mins']))\n",
    "    except ValueError:\n",
    "        return\n",
    "\n",
    "def shuffle(mapper_out): \n",
    "    #Organise the mapped values by key\n",
    "    data = {} \n",
    "    for k, v in filter(None, mapper_out): \n",
    "        if k not in data: \n",
    "            data[k] = [v] \n",
    "        else: \n",
    "            data[k].append(v) \n",
    "    return data\n",
    "\n",
    "def reduce(kv):\n",
    "    k, v = kv\n",
    "    count = [x[0] for x in v]\n",
    "    distances = [x[1] for x in v]\n",
    "    flight_times = [x[2] for x in v]\n",
    "    return k, sum(count), sum(distances), sum(flight_times)\n",
    "\n",
    "\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "ca714289",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "IMPORT MODULES - Start\n",
      "IMPORT MODULES - Failed\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/h3/lldh0c4j02962dvm357kt4080000gn/T/ipykernel_45086/3660960729.py\", line 9, in <module>\n",
      "    import multiprocess as mp\n",
      "ModuleNotFoundError: No module named 'multiprocess'\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "'tuple' object has no attribute 'tb_frame'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[2], line 9\u001b[0m\n\u001b[1;32m      8\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mos\u001b[39;00m\n\u001b[0;32m----> 9\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mmultiprocess\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m \u001b[38;5;21;01mmp\u001b[39;00m\n\u001b[1;32m     10\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mpandas\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m \u001b[38;5;21;01mpd\u001b[39;00m\n",
      "\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'multiprocess'",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mSystemExit\u001b[0m                                Traceback (most recent call last)",
      "    \u001b[0;31m[... skipping hidden 1 frame]\u001b[0m\n",
      "Cell \u001b[0;32mIn[2], line 16\u001b[0m\n\u001b[1;32m     15\u001b[0m     traceback\u001b[38;5;241m.\u001b[39mprint_exc()\n\u001b[0;32m---> 16\u001b[0m     sys\u001b[38;5;241m.\u001b[39mexit(\u001b[38;5;241m1\u001b[39m)  \u001b[38;5;66;03m# Exit with non-zero status code to indicate an error\u001b[39;00m\n\u001b[1;32m     19\u001b[0m \u001b[38;5;66;03m#==========================================================================================\u001b[39;00m\n\u001b[1;32m     20\u001b[0m \u001b[38;5;66;03m### OUTPUT FOLDER CREATION ###\u001b[39;00m\n\u001b[1;32m     21\u001b[0m \u001b[38;5;66;03m#==========================================================================================\u001b[39;00m\n",
      "\u001b[0;31mSystemExit\u001b[0m: 1",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "    \u001b[0;31m[... skipping hidden 1 frame]\u001b[0m\n",
      "File \u001b[0;32m~/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py:2092\u001b[0m, in \u001b[0;36mInteractiveShell.showtraceback\u001b[0;34m(self, exc_tuple, filename, tb_offset, exception_only, running_compiled_code)\u001b[0m\n\u001b[1;32m   2089\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m exception_only:\n\u001b[1;32m   2090\u001b[0m     stb \u001b[38;5;241m=\u001b[39m [\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mAn exception has occurred, use \u001b[39m\u001b[38;5;124m%\u001b[39m\u001b[38;5;124mtb to see \u001b[39m\u001b[38;5;124m'\u001b[39m\n\u001b[1;32m   2091\u001b[0m            \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mthe full traceback.\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m'\u001b[39m]\n\u001b[0;32m-> 2092\u001b[0m     stb\u001b[38;5;241m.\u001b[39mextend(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mInteractiveTB\u001b[38;5;241m.\u001b[39mget_exception_only(etype,\n\u001b[1;32m   2093\u001b[0m                                                      value))\n\u001b[1;32m   2094\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m   2095\u001b[0m     \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m   2096\u001b[0m         \u001b[38;5;66;03m# Exception classes can customise their traceback - we\u001b[39;00m\n\u001b[1;32m   2097\u001b[0m         \u001b[38;5;66;03m# use this in IPython.parallel for exceptions occurring\u001b[39;00m\n\u001b[1;32m   2098\u001b[0m         \u001b[38;5;66;03m# in the engines. This should return a list of strings.\u001b[39;00m\n",
      "File \u001b[0;32m~/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py:644\u001b[0m, in \u001b[0;36mListTB.get_exception_only\u001b[0;34m(self, etype, value)\u001b[0m\n\u001b[1;32m    636\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mget_exception_only\u001b[39m(\u001b[38;5;28mself\u001b[39m, etype, value):\n\u001b[1;32m    637\u001b[0m \u001b[38;5;250m    \u001b[39m\u001b[38;5;124;03m\"\"\"Only print the exception type and message, without a traceback.\u001b[39;00m\n\u001b[1;32m    638\u001b[0m \n\u001b[1;32m    639\u001b[0m \u001b[38;5;124;03m    Parameters\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    642\u001b[0m \u001b[38;5;124;03m    value : exception value\u001b[39;00m\n\u001b[1;32m    643\u001b[0m \u001b[38;5;124;03m    \"\"\"\u001b[39;00m\n\u001b[0;32m--> 644\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m ListTB\u001b[38;5;241m.\u001b[39mstructured_traceback(\u001b[38;5;28mself\u001b[39m, etype, value)\n",
      "File \u001b[0;32m~/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py:511\u001b[0m, in \u001b[0;36mListTB.structured_traceback\u001b[0;34m(self, etype, evalue, etb, tb_offset, context)\u001b[0m\n\u001b[1;32m    508\u001b[0m     chained_exc_ids\u001b[38;5;241m.\u001b[39madd(\u001b[38;5;28mid\u001b[39m(exception[\u001b[38;5;241m1\u001b[39m]))\n\u001b[1;32m    509\u001b[0m     chained_exceptions_tb_offset \u001b[38;5;241m=\u001b[39m \u001b[38;5;241m0\u001b[39m\n\u001b[1;32m    510\u001b[0m     out_list \u001b[38;5;241m=\u001b[39m (\n\u001b[0;32m--> 511\u001b[0m         \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mstructured_traceback(\n\u001b[1;32m    512\u001b[0m             etype, evalue, (etb, chained_exc_ids),\n\u001b[1;32m    513\u001b[0m             chained_exceptions_tb_offset, context)\n\u001b[1;32m    514\u001b[0m         \u001b[38;5;241m+\u001b[39m chained_exception_message\n\u001b[1;32m    515\u001b[0m         \u001b[38;5;241m+\u001b[39m out_list)\n\u001b[1;32m    517\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m out_list\n",
      "File \u001b[0;32m~/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py:1310\u001b[0m, in \u001b[0;36mAutoFormattedTB.structured_traceback\u001b[0;34m(self, etype, value, tb, tb_offset, number_of_lines_of_context)\u001b[0m\n\u001b[1;32m   1308\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m   1309\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mtb \u001b[38;5;241m=\u001b[39m tb\n\u001b[0;32m-> 1310\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m FormattedTB\u001b[38;5;241m.\u001b[39mstructured_traceback(\n\u001b[1;32m   1311\u001b[0m     \u001b[38;5;28mself\u001b[39m, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "File \u001b[0;32m~/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py:1199\u001b[0m, in \u001b[0;36mFormattedTB.structured_traceback\u001b[0;34m(self, etype, value, tb, tb_offset, number_of_lines_of_context)\u001b[0m\n\u001b[1;32m   1196\u001b[0m mode \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mmode\n\u001b[1;32m   1197\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m mode \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mverbose_modes:\n\u001b[1;32m   1198\u001b[0m     \u001b[38;5;66;03m# Verbose modes need a full traceback\u001b[39;00m\n\u001b[0;32m-> 1199\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m VerboseTB\u001b[38;5;241m.\u001b[39mstructured_traceback(\n\u001b[1;32m   1200\u001b[0m         \u001b[38;5;28mself\u001b[39m, etype, value, tb, tb_offset, number_of_lines_of_context\n\u001b[1;32m   1201\u001b[0m     )\n\u001b[1;32m   1202\u001b[0m \u001b[38;5;28;01melif\u001b[39;00m mode \u001b[38;5;241m==\u001b[39m \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mMinimal\u001b[39m\u001b[38;5;124m'\u001b[39m:\n\u001b[1;32m   1203\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m ListTB\u001b[38;5;241m.\u001b[39mget_exception_only(\u001b[38;5;28mself\u001b[39m, etype, value)\n",
      "File \u001b[0;32m~/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py:1052\u001b[0m, in \u001b[0;36mVerboseTB.structured_traceback\u001b[0;34m(self, etype, evalue, etb, tb_offset, number_of_lines_of_context)\u001b[0m\n\u001b[1;32m   1043\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mstructured_traceback\u001b[39m(\n\u001b[1;32m   1044\u001b[0m     \u001b[38;5;28mself\u001b[39m,\n\u001b[1;32m   1045\u001b[0m     etype: \u001b[38;5;28mtype\u001b[39m,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m   1049\u001b[0m     number_of_lines_of_context: \u001b[38;5;28mint\u001b[39m \u001b[38;5;241m=\u001b[39m \u001b[38;5;241m5\u001b[39m,\n\u001b[1;32m   1050\u001b[0m ):\n\u001b[1;32m   1051\u001b[0m \u001b[38;5;250m    \u001b[39m\u001b[38;5;124;03m\"\"\"Return a nice text document describing the traceback.\"\"\"\u001b[39;00m\n\u001b[0;32m-> 1052\u001b[0m     formatted_exception \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mformat_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n\u001b[1;32m   1053\u001b[0m                                                            tb_offset)\n\u001b[1;32m   1055\u001b[0m     colors \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mColors  \u001b[38;5;66;03m# just a shorthand + quicker name lookup\u001b[39;00m\n\u001b[1;32m   1056\u001b[0m     colorsnormal \u001b[38;5;241m=\u001b[39m colors\u001b[38;5;241m.\u001b[39mNormal  \u001b[38;5;66;03m# used a lot\u001b[39;00m\n",
      "File \u001b[0;32m~/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py:953\u001b[0m, in \u001b[0;36mVerboseTB.format_exception_as_a_whole\u001b[0;34m(self, etype, evalue, etb, number_of_lines_of_context, tb_offset)\u001b[0m\n\u001b[1;32m    950\u001b[0m \u001b[38;5;28;01massert\u001b[39;00m \u001b[38;5;28misinstance\u001b[39m(tb_offset, \u001b[38;5;28mint\u001b[39m)\n\u001b[1;32m    951\u001b[0m head \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mprepare_header(etype, \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mlong_header)\n\u001b[1;32m    952\u001b[0m records \u001b[38;5;241m=\u001b[39m (\n\u001b[0;32m--> 953\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mget_records(etb, number_of_lines_of_context, tb_offset) \u001b[38;5;28;01mif\u001b[39;00m etb \u001b[38;5;28;01melse\u001b[39;00m []\n\u001b[1;32m    954\u001b[0m )\n\u001b[1;32m    956\u001b[0m frames \u001b[38;5;241m=\u001b[39m []\n\u001b[1;32m    957\u001b[0m skipped \u001b[38;5;241m=\u001b[39m \u001b[38;5;241m0\u001b[39m\n",
      "File \u001b[0;32m~/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py:1021\u001b[0m, in \u001b[0;36mVerboseTB.get_records\u001b[0;34m(self, etb, number_of_lines_of_context, tb_offset)\u001b[0m\n\u001b[1;32m   1019\u001b[0m \u001b[38;5;28;01mwhile\u001b[39;00m cf \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[1;32m   1020\u001b[0m     \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m-> 1021\u001b[0m         source_file \u001b[38;5;241m=\u001b[39m inspect\u001b[38;5;241m.\u001b[39mgetsourcefile(etb\u001b[38;5;241m.\u001b[39mtb_frame)\n\u001b[1;32m   1022\u001b[0m         lines, first \u001b[38;5;241m=\u001b[39m inspect\u001b[38;5;241m.\u001b[39mgetsourcelines(etb\u001b[38;5;241m.\u001b[39mtb_frame)\n\u001b[1;32m   1023\u001b[0m     \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mOSError\u001b[39;00m:\n",
      "\u001b[0;31mAttributeError\u001b[0m: 'tuple' object has no attribute 'tb_frame'"
     ]
    }
   ],
   "source": [
    "#==========================================================================================\n",
    "### IMPORT MODULES ###\n",
    "#==========================================================================================\n",
    "try:\n",
    "    print(\"IMPORT MODULES - Start\")\n",
    "    import sys\n",
    "    import traceback\n",
    "    import os\n",
    "    import multiprocess as mp\n",
    "    import pandas as pd\n",
    "    from geopy.distance import geodesic\n",
    "    print(\"IMPORT MODULES - Success\")\n",
    "except:\n",
    "    print(\"IMPORT MODULES - Failed\")\n",
    "    traceback.print_exc()\n",
    "    sys.exit(1)  # Exit with non-zero status code to indicate an error\n",
    "\n",
    "\n",
    "#==========================================================================================\n",
    "### OUTPUT FOLDER CREATION ###\n",
    "#==========================================================================================\n",
    "try:\n",
    "    print(\"OUTPUT FOLDER CREATION - Start\")\n",
    "    if not os.path.exists(\"output_folder\"):\n",
    "        os.makedirs(\"output_folder\")\n",
    "    else:\n",
    "        print(\"output_folder already exists\")\n",
    "    print(\"OUTPUT FOLDER CREATION- Success\")\n",
    "except:\n",
    "    print(\"OUTPUT FOLDER CREATION - Failed\")\n",
    "    traceback.print_exc()\n",
    "    sys.exit(1)  # Exit with non-zero status code to indicate an error\n",
    "\n",
    "\n",
    "#==========================================================================================\n",
    "### LOAD INPUT AND PREPROCESSING ###\n",
    "#==========================================================================================\n",
    "try:\n",
    "    print(\"LOAD INPUT AND PREPROCESSING - Start\")\n",
    "    header_names_1 = [\"Passenger_id\", \"Flight_id\", \"From_airport_IATA\", \"Destination_airport_IATA\",\n",
    "                      \"Departure_time_GMT\", \"Total_flight_time_mins\"]\n",
    "    df_1 = pd.read_csv('AComp_Passenger_data_no_error.csv', encoding='utf-8', header=None, names=header_names_1)\n",
    "\n",
    "    header_names_2 = [\"From_Airport_Name\", \"From_Airport_IATA\", \"From_Latitude\", \"From_Longitude\"]\n",
    "    df_2 = pd.read_csv('Top30_airports_LatLong.csv', encoding='utf-8', header=None, names=header_names_2)\n",
    "    df = pd.merge(df_1, df_2, how='left', left_on=\"From_airport_IATA\", right_on=\"From_Airport_IATA\")\n",
    "\n",
    "    header_names_2 = [\"To_Airport_Name\", \"To_Airport_IATA\", \"To_Latitude\", \"To_Longitude\"]\n",
    "    df_2 = pd.read_csv('Top30_airports_LatLong.csv', encoding='utf-8', header=None, names=header_names_2)\n",
    "    df = pd.merge(df, df_2, how='left', left_on=\"Destination_airport_IATA\", right_on=\"To_Airport_IATA\")\n",
    "\n",
    "    df['Distance_km'] = df.apply(lambda row: geodesic((row['From_Latitude'], row['From_Longitude']), \n",
    "                                                           (row['To_Latitude'], row['To_Longitude'])).kilometers, axis=1)\n",
    "    print(\"LOAD INPUT AND PREPROCESSING - Success\")\n",
    "except:\n",
    "    print(\"LOAD INPUT AND PREPROCESSING - Failed\")\n",
    "    traceback.print_exc()\n",
    "    sys.exit(1)  # Exit with non-zero status code to indicate an error\n",
    "\n",
    "\n",
    "#==========================================================================================\n",
    "### MAPREDUCE BEFORE REMOVING DUPLICATE VALUES ###\n",
    "#==========================================================================================\n",
    "try:\n",
    "    print(\"MAPREDUCE BEFORE REMOVING DUPLICATE VALUES - Start\")\n",
    "    # Perform map-reduce operations using multiprocessing\n",
    "    with mp.get_context('spawn').Pool(processes=mp.cpu_count()) as pool:\n",
    "        map_out = pool.map(map_function, df.to_dict('records'))\n",
    "        reduce_in = shuffle(map_out)\n",
    "        reduce_out = pool.map(reduce, reduce_in.items())\n",
    "        reduce_out_df_1 = pd.DataFrame(reduce_out, columns=['Passenger_id', 'total flights', 'Distance_km', 'Total_flight_time_mins'])\n",
    "        reduce_out_df_1.sort_values(by=['total flights', 'Distance_km', 'Total_flight_time_mins'], ascending=False, inplace =True)\n",
    "        print(\"Print top six passengers\")\n",
    "        print(reduce_out_df_1.head(6))\n",
    "        print(\"________________________________\")\n",
    "        print(f'Saving file as {os.path.join(\"output_folder\", \"reduce_out_BEFORE_duplicate_values.csv\")}')\n",
    "        reduce_out_df_1.to_csv(os.path.join(\"output_folder\", \"reduce_out_BEFORE_duplicate_values.csv\"), index=False)\n",
    "    print(\"MAPREDUCE BEFORE REMOVING DUPLICATE VALUES - Success\")\n",
    "except:\n",
    "    print(\"MAPREDUCE BEFORE REMOVING DUPLICATE VALUES- Failed\")\n",
    "    traceback.print_exc()\n",
    "    sys.exit(1)  # Exit with non-zero status code to indicate an error\n",
    "\n",
    "#==========================================================================================\n",
    "### MAPREDUCE AFTER REMOVING DUPLICATE VALUES ###\n",
    "#==========================================================================================\n",
    "try:\n",
    "    print(\"MAPREDUCE AFTER REMOVING DUPLICATE VALUES - Start\")\n",
    "    df.drop_duplicates(inplace=True) #drop duplicates\n",
    "\n",
    "    # Perform map-reduce operations using multiprocessing\n",
    "    with mp.get_context('spawn').Pool(processes=mp.cpu_count()) as pool:\n",
    "        map_out = pool.map(map, df.to_dict('records'))\n",
    "        reduce_in = shuffle(map_out)\n",
    "        reduce_out = pool.map(reduce, reduce_in.items())\n",
    "        reduce_out_df_2 = pd.DataFrame(reduce_out, columns=['Passenger_id', 'total flights', 'Distance_km', 'Total_flight_time_mins'])\n",
    "        reduce_out_df_2.sort_values(by=['total flights', 'Distance_km', 'Total_flight_time_mins'], ascending=False, inplace =True)\n",
    "        print(\"Print top six passengers\")\n",
    "        print(reduce_out_df_2.head(6))\n",
    "        print(\"-----------------\")\n",
    "        print(f'Saving file as {os.path.join(\"output_folder\", \"reduce_out_AFTER_duplicate_values.csv\")}')\n",
    "        reduce_out_df_2.to_csv(os.path.join(\"output_folder\", \"reduce_out_AFTER_duplicate_values.csv\"), index=False)\n",
    "        print(\"MAPREDUCE AFTER REMOVING DUPLICATE VALUES - Success\")\n",
    "except:\n",
    "    print(\"MAPREDUCE AFTER REMOVING DUPLICATE VALUES- Failed\")\n",
    "    traceback.print_exc()\n",
    "    sys.exit(1)  # Exit with non-zero status code to indicate an error\n",
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ca8219e8",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
